FROM php:8.1-apache

# Installer Git, Node.js, et les dépendances système
RUN apt-get update && apt-get install -y \
  git \
  curl \
  zip \
  unzip

# Installer Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copier la configuration Apache personnalisée
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

# Activer le module rewrite
RUN a2enmod rewrite

# Activer le module mysql
RUN apt-get update && apt-get install -y \
  libfreetype6-dev \
  libjpeg62-turbo-dev \
  libpng-dev \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install -j$(nproc) gd \
  && docker-php-ext-install pdo_mysql \
  && docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN php -m | grep pdo_mysql

# Set the working directory
WORKDIR /var/www/html

# Clone the repository
RUN git clone https://github.com/Boutroisjordan/vide-grenier-cube.git .
# ADD package*.json /var/www/html

# Installer les dépendances Node.js
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs
RUN npm install


# Installer les dépendances PHP
# ADD composer.* /var/www/html

# Installer les dépendances PHP avec Composer
RUN composer install
RUN composer update

ADD ./App/Config.php /var/www/html/App/

# Définir les permissions pour les fichiers du projet
RUN chown -R www-data:www-data /var/www/html

# Exposer le port 80 (Apache)
EXPOSE 80
