version: '3.9'

services:
  mySql:
    image: mysql:8.0.33
    container_name: mySql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: vide_grenier
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  project:
    build:
        context: .
        dockerfile: dockerFile.yml
    container_name: project
    ports:
      - "8080:8080"
    command: >
      bash -c "
        git clone https://github.com/Boutroisjordan/vide-grenier-cube.git /app
        npm install
        npm run build
        composer update
        php -S 0.0.0.0:8080 -t public
      "