version: '3.9'


services:
  mySql:
    image: mysql:8.0.33
    container_name: mySql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: vide_grenier
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  apache:
    build:
      context: .
      dockerfile: dockerFile.prod.yml
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mySql
