version: '3.9'

services:
  mySql:
    image: mysql:8.0.33
    container_name: mySql_${APP_ENV}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: vide_grenier
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./data/mysql_${APP_ENV}:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  apache:
    build:
        context: .
        dockerfile: dockerfile.yml
        target: ${APP_ENV}
    container_name: apache_${APP_ENV}
    environment:
      - APP_ENV
      - APP_PORT
      - MYSQL_PORT
    volumes:
      - ./public/storage:/var/www/html/public/storage
    ports:
      - ${APP_PORT}:80
    depends_on:
      - mySql
