FROM php:7.4-apache

# Installer Git, Node.js, et les dépendances système
RUN apt-get update && apt-get install -y \
  git \
  curl \
  zip \
  unzip

# Installer Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copier la configuration Apache personnalisée
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

# Activer le module rewrite
RUN a2enmod rewrite

# Set the working directory
WORKDIR /var/www/html

# Clone the repository
# RUN git clone https://github.com/Boutroisjordan/vide-grenier-cube.git .

COPY . /var/www/html

# Installer les dépendances Node.js
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs
RUN npm install

# Installer les dépendances PHP avec Composer
RUN composer install --no-dev --optimize-autoloader
RUN composer update



# Définir les permissions pour les fichiers du projet
RUN chown -R www-data:www-data /var/www/html

# Activer la PDO PHP
# RUN php -m|grep -i pdo_mysql

RUN apt-get update && apt-get install -y \
  libfreetype6-dev \
  libjpeg62-turbo-dev \
  libpng-dev \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install -j$(nproc) gd \
  && docker-php-ext-install pdo_mysql

# Exposer le port 80 (Apache)
EXPOSE 80